/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_CoefficientOfFriction_H_
#define	_CoefficientOfFriction_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CoefficientOfFriction */
typedef long	 CoefficientOfFriction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoefficientOfFriction;
asn_struct_free_f CoefficientOfFriction_free;
asn_struct_print_f CoefficientOfFriction_print;
asn_constr_check_f CoefficientOfFriction_constraint;
ber_type_decoder_f CoefficientOfFriction_decode_ber;
der_type_encoder_f CoefficientOfFriction_encode_der;
xer_type_decoder_f CoefficientOfFriction_decode_xer;
xer_type_encoder_f CoefficientOfFriction_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CoefficientOfFriction_H_ */
#include <asn_internal.h>
