/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_DriveAxleLocation_H_
#define	_DriveAxleLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DriveAxleLocation */
typedef long	 DriveAxleLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DriveAxleLocation;
asn_struct_free_f DriveAxleLocation_free;
asn_struct_print_f DriveAxleLocation_print;
asn_constr_check_f DriveAxleLocation_constraint;
ber_type_decoder_f DriveAxleLocation_decode_ber;
der_type_encoder_f DriveAxleLocation_encode_der;
xer_type_decoder_f DriveAxleLocation_decode_xer;
xer_type_encoder_f DriveAxleLocation_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DriveAxleLocation_H_ */
#include <asn_internal.h>
