/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_SpecialLane_H_
#define	_SpecialLane_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LaneNumber.h"
#include "LaneWidth.h"
#include "SpecialLaneAttributes.h"
#include "NodeList.h"
#include "ConnectsTo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeList;

/* SpecialLane */
typedef struct SpecialLane {
	LaneNumber_t	 laneNumber;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	SpecialLaneAttributes_t	 laneAttributes;
	NodeList_t	 nodeList;
	struct NodeList	*keepOutList	/* OPTIONAL */;
	ConnectsTo_t	*connectsTo	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpecialLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpecialLane;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NodeList.h"

#endif	/* _SpecialLane_H_ */
#include <asn_internal.h>
