/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_SpeedLimit_H_
#define	_SpeedLimit_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "ITIScodes.h"
#include <IA5String.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum item3_PR {
	item3_PR_NOTHING,	/* No components present */
	item3_PR_itis3,
	item3_PR_text3
} item3_PR;

/* SpeedLimit */
typedef struct SpeedLimit {
	A_SEQUENCE_OF(struct Member4 {
		struct item3 {
			item3_PR present;
			union item3_u {
				ITIScodes_t	 itis3;
				IA5String_t	 text3;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} item3;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpeedLimit_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedLimit;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedLimit_H_ */
#include <asn_internal.h>
