#!/bin/bash

# @file run_init
# @author  
# @author  Mani Amoozadeh
# @date    Jul 2016
#
# @section LICENSE
#
# This software embodies materials and concepts that are confidential to Redpine
# Signals and is made available solely pursuant to the terms of a written license
# agreement with Redpine Signals
#
# @section DESCRIPTION
#
# This bash script runs the rsi_1609 application
#


if [ "$EUID" -ne 0 ]; then 
  printf "\e[1;31mRun the script with sudo permission! \e[0m \n\n"
  exit 1
fi


if ! pgrep rsi_1609 > /dev/null; then 
  sudo ../rsi_1609
else
  echo "rsi_1609 is already running!"  
fi
