#!/bin/bash

# @file run_init
# @author  
# @author  Mani Amoozadeh
# @date    Apr 2016
#
# @section LICENSE
#
# This software embodies materials and concepts that are confidential to Redpine
# Signals and is made available solely pursuant to the terms of a written license
# agreement with Redpine Signals
#
# @section DESCRIPTION
#
# This bash script prepare the Redpine board to run WAVE applications
#


if [ "$EUID" -ne 0 ]; then 
  printf "\e[1;31mRun the script with sudo permission! \e[0m \n\n"
  exit 1
fi

echo "Bash version is: $BASH_VERSION"


##############
## Check OS ##
##############

OS='unknown'
CODENAME='unknown'
VER='unknown'
ARCH='unknown'

# get current OS information
if [[ "$OSTYPE" == "linux-gnu" || "$OSTYPE" == "linux-gnueabihf" ]]; then
    # Ubuntu
    OS=$(lsb_release -si)
    VER=$(lsb_release -sr)
    CODENAME=$(lsb_release -sc)
    ARCH=$(uname -m)
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
    OS=$(sw_vers -productName)
    VER=$(sw_vers -productVersion)
    ARCH=$(uname -m)
fi

echo "Detected OS:" $OSTYPE $OS $VER "("$CODENAME")", $ARCH


##################
## function def ##
##################

insert_module ()
{
    declare -a argAry=("${!1}")
    for i in "${argAry[@]}"
    do
        # check if module $i is already loaded
        noSpace=$(echo $i | sed 's/ .*//')
        echo -n $noSpace "..."
        base=${i%.*}
        PKG_OK=$(lsmod 2> /dev/null | grep $base)
        if [ "" == "$PKG_OK" ]; then
            sudo insmod $i > /dev/null
            if [[ $? -ne 0 ]]; then
                exit 1
            fi
            echo "done!"
        else
            echo "already loaded!"
        fi
    done
}


####################
## Starting point ##
####################

# build the test_init program
make -B all
if [[ $? -ne 0 ]]; then
   	exit 1
fi
	
# check if all drivers are loaded
./test_init

# if not, then load the drivers
if [[ $? -ne 0 ]]; then

	cd ..

	echo ""
	echo "Inserting modules into kernel"
	echo "============================="

	modu=("onebox_common_gpl.ko")
	insert_module modu[@]

	# load WLAN modules
	modu=("wlan.ko" "wlan_wep.ko" "wlan_tkip.ko" "wlan_ccmp.ko" "wlan_acl.ko" "wlan_xauth.ko" "wlan_scan_sta.ko" "onebox_wlan_nongpl.ko" "onebox_wlan_gpl.ko")
	insert_module modu[@]

	echo ""
	echo "Loading parameters"
	echo "=================="

	# Do not delete/change the following line!
	# [params]

	# show each parameter in a separate line
	IFS=' ' read -ra TOKENS <<< "$PARAMS"
	for i in "${TOKENS[@]}"; do
    	echo "$i"
	done

	# load common HAL modules
	echo ""
	modu=("onebox_nongpl.ko	$PARAMS" "onebox_gpl.ko")
	insert_module modu[@]

	echo ""
	echo "ANT_SEL REG value"
	echo "================="

	sleep 1

	./onebox_util rpine0 ant_sel 2
	if [[ $? -ne 0 ]]; then
    	exit 1
	fi

	sleep 1

	./onebox_util rpine0 ant_sel 5
	if [[ $? -ne 0 ]]; then
    	exit 1
	fi

	echo ""
	echo "Next step"
	echo "========="

	sleep 0.5

	./onebox_util rpine0 create_vap wifi0 wave
	if [[ $? -ne 0 ]]; then
    	exit 1
	fi

	sleep 0.5

	sleep 1

	./onebox_util rpine0 set_country 840
	if [[ $? -ne 0 ]]; then
    	exit 1
	fi

	sleep 0.5

	ifconfig wifi0 up
	if [[ $? -ne 0 ]]; then
    	exit 1
	fi

	echo ""
	echo "Running WAVE"
	echo "============"

	iwpriv wifi0 mode 8
	if [[ $? -ne 0 ]]; then
    	exit 1
	fi

	./onebox_util rpine0 set_chwidth 16
	if [[ $? -ne 0 ]]; then
    	exit 1
	fi

	./onebox_util rpine0 set_channel 178
	if [[ $? -ne 0 ]]; then
    	exit 1
	fi

fi
