//
// Generated file, do not edit! Created by nedtool 4.6 from PhyControlMessage.msg.
//

#ifndef _PHYCONTROLMESSAGE_M_H_
#define _PHYCONTROLMESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>PhyControlMessage.msg:22</tt> by nedtool.
 * <pre>
 * //
 * // Defines a control message that can be associated with a MAC frame to set
 * // transmission power and datarate on a per packet basis
 * //
 * message PhyControlMessage
 * {
 *     //modulation and coding scheme to be used (see enum TxMCS in ConstsPhy.h)
 *     int mcs;
 *     //transmission power to be used in mW
 *     double txPower_mW;
 * }
 * </pre>
 */
class PhyControlMessage : public ::cMessage
{
  protected:
    int mcs_var;
    double txPower_mW_var;

  private:
    void copy(const PhyControlMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PhyControlMessage&);

  public:
    PhyControlMessage(const char *name=NULL, int kind=0);
    PhyControlMessage(const PhyControlMessage& other);
    virtual ~PhyControlMessage();
    PhyControlMessage& operator=(const PhyControlMessage& other);
    virtual PhyControlMessage *dup() const {return new PhyControlMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getMcs() const;
    virtual void setMcs(int mcs);
    virtual double getTxPower_mW() const;
    virtual void setTxPower_mW(double txPower_mW);
};

inline void doPacking(cCommBuffer *b, PhyControlMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PhyControlMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _PHYCONTROLMESSAGE_M_H_

