/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

// Check the standard here: http://standards.sae.org/j2735_201603/

#ifndef	_AllInclusive_H_
#define	_AllInclusive_H_

#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/AccelerationSet4Way.h>
#include <SAE_J2735/AntennaOffsetSet.h>
#include <SAE_J2735/BrakeSystemStatus.h>
#include <SAE_J2735/BSMblob.h>
#include <SAE_J2735/ConnectsTo.h>
#include <SAE_J2735/Offsets.h>
#include <SAE_J2735/PathHistoryPointType-02.h>
#include <SAE_J2735/PathHistoryPointType-03.h>
#include <SAE_J2735/PathHistoryPointType-04.h>
#include <SAE_J2735/PathHistoryPointType-05.h>
#include <SAE_J2735/PathHistoryPointType-06.h>
#include <SAE_J2735/PathHistoryPointType-07.h>
#include <SAE_J2735/PathHistoryPointType-08.h>
#include <SAE_J2735/PathHistoryPointType-09.h>
#include <SAE_J2735/PathHistoryPointType-10.h>
#include <SAE_J2735/PositionalAccuracy.h>
#include <SAE_J2735/PositionConfidenceSet.h>
#include <SAE_J2735/RTCMHeader.h>
#include <SAE_J2735/SpeedandHeadingandThrottleConfidence.h>
#include <SAE_J2735/TransmissionAndSpeed.h>
#include <SAE_J2735/Acceleration.h>
#include <SAE_J2735/AccelerationConfidence.h>
#include <SAE_J2735/AmbientAirPressure.h>
#include <SAE_J2735/AmbientAirTemperature.h>
#include <SAE_J2735/AntiLockBrakeStatus.h>
#include <SAE_J2735/ApproachNumber.h>
#include <SAE_J2735/AuxiliaryBrakeStatus.h>
#include <SAE_J2735/BarrierAttributes.h>
#include <SAE_J2735/BrakeAppliedPressure.h>
#include <SAE_J2735/BrakeAppliedStatus.h>
#include <SAE_J2735/BrakeBoostApplied.h>
#include <SAE_J2735/BumperHeightFront.h>
#include <SAE_J2735/BumperHeightRear.h>
#include <SAE_J2735/CodeWord.h>
#include <SAE_J2735/CoefficientOfFriction.h>
#include <SAE_J2735/ColorState.h>
#include <SAE_J2735/Count.h>
#include <SAE_J2735/CrosswalkLaneAttributes.h>
#include <SAE_J2735/DDay.h>
#include <SAE_J2735/DescriptiveName.h>
#include <SAE_J2735/DHour.h>
#include <SAE_J2735/DirectionOfUse.h>
#include <SAE_J2735/DMinute.h>
#include <SAE_J2735/DMonth.h>
#include <SAE_J2735/DOffset.h>
#include <SAE_J2735/DrivenLineOffset.h>
#include <SAE_J2735/DrivingWheelAngle.h>
#include <SAE_J2735/DSecond.h>
#include <SAE_J2735/DSignalSeconds.h>
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/DYear.h>
#include <SAE_J2735/ElevationConfidence.h>
#include <SAE_J2735/Elevation.h>
#include <SAE_J2735/EmergencyDetails.h>
#include <SAE_J2735/EventFlags.h>
#include <SAE_J2735/Extent.h>
#include <SAE_J2735/ExteriorLights.h>
#include <SAE_J2735/FurtherInfoID.h>
#include <SAE_J2735/GPSstatus.h>
#include <SAE_J2735/HeadingConfidence.h>
#include <SAE_J2735/Heading.h>
#include <SAE_J2735/HeadingSlice.h>
#include <SAE_J2735/IntersectionStatusObject.h>
#include <SAE_J2735/IntersectionID.h>
#include <SAE_J2735/AxleLocation.h>
#include <SAE_J2735/AxleWeight.h>
#include <SAE_J2735/CargoWeight.h>
#include <SAE_J2735/DriveAxleLiftAirPressure.h>
#include <SAE_J2735/DriveAxleLocation.h>
#include <SAE_J2735/DriveAxleLubePressure.h>
#include <SAE_J2735/DriveAxleTemperature.h>
#include <SAE_J2735/SteeringAxleLubePressure.h>
#include <SAE_J2735/SteeringAxleTemperature.h>
#include <SAE_J2735/TireLeakageRate.h>
#include <SAE_J2735/TireLocation.h>
#include <SAE_J2735/TirePressureThresholdDetection.h>
#include <SAE_J2735/TirePressure.h>
#include <SAE_J2735/TireTemp.h>
#include <SAE_J2735/TrailerWeight.h>
#include <SAE_J2735/WheelEndElectFault.h>
#include <SAE_J2735/WheelSensorStatus.h>
#include <SAE_J2735/LaneCount.h>
#include <SAE_J2735/LaneManeuverCode.h>
#include <SAE_J2735/LaneNumber.h>
#include <SAE_J2735/LaneSet.h>
#include <SAE_J2735/LaneWidth.h>
#include <SAE_J2735/Latitude.h>
#include <SAE_J2735/LayerID.h>
#include <SAE_J2735/LayerType.h>
#include <SAE_J2735/LightbarInUse.h>
#include <SAE_J2735/Longitude.h>
#include <SAE_J2735/Location-quality.h>
#include <SAE_J2735/Location-tech.h>
#include <SAE_J2735/MinuteOfTheYear.h>
#include <SAE_J2735/MinutesDuration.h>
#include <SAE_J2735/MsgCount.h>
#include <SAE_J2735/MsgCRC.h>
#include <SAE_J2735/MultiVehicleResponse.h>
#include <SAE_J2735/MUTCDCode.h>
#include <SAE_J2735/NMEA-MsgType.h>
#include <SAE_J2735/NMEA-Payload.h>
#include <SAE_J2735/NMEA-Revision.h>
#include <SAE_J2735/NTCIPVehicleclass.h>
#include <SAE_J2735/ObjectCount.h>
#include <SAE_J2735/ObstacleDirection.h>
#include <SAE_J2735/ObstacleDistance.h>
#include <SAE_J2735/PayloadData.h>
#include <SAE_J2735/Payload.h>
#include <SAE_J2735/PedestrianDetect.h>
#include <SAE_J2735/PedestrianSignalState.h>
#include <SAE_J2735/PositionConfidence.h>
#include <SAE_J2735/PreemptState.h>
#include <SAE_J2735/Priority.h>
#include <SAE_J2735/PriorityState.h>
#include <SAE_J2735/ProbeSegmentNumber.h>
#include <SAE_J2735/RainSensor.h>
#include <SAE_J2735/RequestedItem.h>
#include <SAE_J2735/ResponseType.h>
#include <SAE_J2735/RTCM-ID.h>
#include <SAE_J2735/RTCM-Payload.h>
#include <SAE_J2735/RTCM-Revision.h>
#include <SAE_J2735/SignalLightState.h>
#include <SAE_J2735/SignalReqScheme.h>
#include <SAE_J2735/SignalState.h>
#include <SAE_J2735/SignPrority.h>
#include <SAE_J2735/SirenInUse.h>
#include <SAE_J2735/SpecialLaneAttributes.h>
#include <SAE_J2735/SpecialSignalState.h>
#include <SAE_J2735/SpeedConfidence.h>
#include <SAE_J2735/Speed.h>
#include <SAE_J2735/StabilityControlStatus.h>
#include <SAE_J2735/StateConfidence.h>
#include <SAE_J2735/SteeringWheelAngleConfidence.h>
#include <SAE_J2735/SteeringWheelAngleRateOfChange.h>
#include <SAE_J2735/SteeringWheelAngle.h>
#include <SAE_J2735/SunSensor.h>
#include <SAE_J2735/TemporaryID.h>
#include <SAE_J2735/TermDistance.h>
#include <SAE_J2735/TermTime.h>
#include <SAE_J2735/ThrottleConfidence.h>
#include <SAE_J2735/ThrottlePosition.h>
#include <SAE_J2735/TimeConfidence.h>
#include <SAE_J2735/TimeMark.h>
#include <SAE_J2735/TractionControlState.h>
#include <SAE_J2735/TransitPreEmptionRequest.h>
#include <SAE_J2735/TransitStatus.h>
#include <SAE_J2735/TransmissionState.h>
#include <SAE_J2735/TxTime.h>
#include <SAE_J2735/TravelerInfoType.h>
#include <SAE_J2735/UniqueMSGID.h>
#include <SAE_J2735/URL-Base.h>
#include <SAE_J2735/URL-Link.h>
#include <SAE_J2735/URL-Short.h>
#include <SAE_J2735/VehicleHeight.h>
#include <SAE_J2735/VehicleLaneAttributes.h>
#include <SAE_J2735/VehicleLength.h>
#include <SAE_J2735/VehicleMass.h>
#include <SAE_J2735/VehicleRequestStatus.h>
#include <SAE_J2735/VehicleStatusDeviceTypeTag.h>
#include <SAE_J2735/VehicleType.h>
#include <SAE_J2735/VehicleWidth.h>
#include <SAE_J2735/VerticalAccelerationThreshold.h>
#include <SAE_J2735/VerticalAcceleration.h>
#include <SAE_J2735/VINstring.h>
#include <SAE_J2735/WiperRate.h>
#include <SAE_J2735/WiperStatusFront.h>
#include <SAE_J2735/WiperStatusRear.h>
#include <SAE_J2735/YawRateConfidence.h>
#include <SAE_J2735/YawRate.h>
#include <SAE_J2735/IncidentResponseEquipment.h>
#include <SAE_J2735/ITIStext.h>
#include <SAE_J2735/ResponderGroupAffected.h>
#include <SAE_J2735/VehicleGroupAffected.h>
#include <SAE_J2735/EssMobileFriction.h>
#include <SAE_J2735/EssPrecipRate.h>
#include <SAE_J2735/EssPrecipSituation.h>
#include <SAE_J2735/EssPrecipYesNo.h>
#include <SAE_J2735/EssSolarRadiation.h>
#include <SAE_J2735/ITIScodes.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AccelSteerYawRateConfidence;
struct Approach;
struct ApproachObject;
struct BarrierLane;
struct BumperHeights;
struct Circle;
struct ConfidenceSet;
struct CrosswalkLane;
struct DataParameters;
struct DDate;
struct DDateTime;
struct DFullTime;
struct DMonthDay;
struct DTime;
struct DYearMonth;
struct FullPositionVector;
struct Intersection;
struct IntersectionState;
struct ExitService;
struct GenericSignage;
struct SpeedLimit;
struct WorkZone;
struct J1939data;
struct MovementState;
struct NodeList;
struct PathHistory;
struct PathHistoryPointType_01;
struct PathPrediction;
struct Position3D;
struct RegionList;
struct RegionOffsets;
struct RegionPointSet;
struct RoadSignID;
struct RTCMmsg;
struct RTCMPackage;
struct Sample;
struct ShapePointSet;
struct SignalControlZone;
struct SignalRequest;
struct SnapshotDistance;
struct Snapshot;
struct SnapshotTime;
struct SpecialLane;
struct ValidRegion;
struct VehicleComputedLane;
struct VehicleIdent;
struct VehicleReferenceLane;
struct VehicleSafetyExtension;
struct VehicleSize;
struct VehicleStatusRequest;
struct VehicleStatus;
struct WiperStatus;
struct ITIScodesAndText;

/* AllInclusive */
typedef struct AllInclusive {
	AccelerationSet4Way_t	*item6_1	/* OPTIONAL */;
	struct AccelSteerYawRateConfidence	*item6_2	/* OPTIONAL */;
	AntennaOffsetSet_t	*item6_4	/* OPTIONAL */;
	struct Approach	*item6_5	/* OPTIONAL */;
	struct ApproachObject	*item6_6	/* OPTIONAL */;
	struct BarrierLane	*item6_7	/* OPTIONAL */;
	BrakeSystemStatus_t	*item6_8	/* OPTIONAL */;
	BSMblob_t	*item6_9	/* OPTIONAL */;
	struct BumperHeights	*item6_10	/* OPTIONAL */;
	struct Circle	*item6_11	/* OPTIONAL */;
	struct ConfidenceSet	*item6_12	/* OPTIONAL */;
	ConnectsTo_t	*item6_13	/* OPTIONAL */;
	struct CrosswalkLane	*item6_14	/* OPTIONAL */;
	struct DataParameters	*item6_15	/* OPTIONAL */;
	struct DDate	*item6_16	/* OPTIONAL */;
	struct DDateTime	*item6_17	/* OPTIONAL */;
	struct DFullTime	*item6_18	/* OPTIONAL */;
	struct DMonthDay	*item6_19	/* OPTIONAL */;
	struct DTime	*item6_20	/* OPTIONAL */;
	struct DYearMonth	*item6_21	/* OPTIONAL */;
	struct FullPositionVector	*item6_22	/* OPTIONAL */;
	struct Intersection	*item6_23	/* OPTIONAL */;
	struct IntersectionState	*item6_24	/* OPTIONAL */;
	struct ExitService	*item6_25	/* OPTIONAL */;
	struct GenericSignage	*item6_26	/* OPTIONAL */;
	struct SpeedLimit	*item6_27	/* OPTIONAL */;
	struct WorkZone	*item6_28	/* OPTIONAL */;
	struct J1939data	*item6_29	/* OPTIONAL */;
	struct MovementState	*item6_30	/* OPTIONAL */;
	struct NodeList	*item6_31	/* OPTIONAL */;
	Offsets_t	*item6_32	/* OPTIONAL */;
	struct PathHistory	*item6_33	/* OPTIONAL */;
	struct PathHistoryPointType_01	*item6_34	/* OPTIONAL */;
	PathHistoryPointType_02_t	*item6_35	/* OPTIONAL */;
	PathHistoryPointType_03_t	*item6_36	/* OPTIONAL */;
	PathHistoryPointType_04_t	*item6_37	/* OPTIONAL */;
	PathHistoryPointType_05_t	*item6_38	/* OPTIONAL */;
	PathHistoryPointType_06_t	*item6_39	/* OPTIONAL */;
	PathHistoryPointType_07_t	*item6_40	/* OPTIONAL */;
	PathHistoryPointType_08_t	*item6_41	/* OPTIONAL */;
	PathHistoryPointType_09_t	*item6_42	/* OPTIONAL */;
	PathHistoryPointType_10_t	*item6_43	/* OPTIONAL */;
	struct PathPrediction	*item6_44	/* OPTIONAL */;
	struct Position3D	*item6_45	/* OPTIONAL */;
	PositionalAccuracy_t	*item6_46	/* OPTIONAL */;
	PositionConfidenceSet_t	*item6_47	/* OPTIONAL */;
	struct RegionList	*item6_48	/* OPTIONAL */;
	struct RegionOffsets	*item6_49	/* OPTIONAL */;
	struct RegionPointSet	*item6_50	/* OPTIONAL */;
	struct RoadSignID	*item6_51	/* OPTIONAL */;
	RTCMHeader_t	*item6_52	/* OPTIONAL */;
	struct RTCMmsg	*item6_53	/* OPTIONAL */;
	struct RTCMPackage	*item6_54	/* OPTIONAL */;
	struct Sample	*item6_55	/* OPTIONAL */;
	struct ShapePointSet	*item6_56	/* OPTIONAL */;
	struct SignalControlZone	*item6_57	/* OPTIONAL */;
	struct SignalRequest	*item6_58	/* OPTIONAL */;
	struct SnapshotDistance	*item6_59	/* OPTIONAL */;
	struct Snapshot	*item6_60	/* OPTIONAL */;
	struct SnapshotTime	*item6_61	/* OPTIONAL */;
	struct SpecialLane	*item6_62	/* OPTIONAL */;
	SpeedandHeadingandThrottleConfidence_t	*item6_63	/* OPTIONAL */;
	TransmissionAndSpeed_t	*item6_64	/* OPTIONAL */;
	struct ValidRegion	*item6_65	/* OPTIONAL */;
	struct VehicleComputedLane	*item6_66	/* OPTIONAL */;
	struct VehicleIdent	*item6_67	/* OPTIONAL */;
	struct VehicleReferenceLane	*item6_68	/* OPTIONAL */;
	struct VehicleSafetyExtension	*item6_69	/* OPTIONAL */;
	struct VehicleSize	*item6_70	/* OPTIONAL */;
	struct VehicleStatusRequest	*item6_71	/* OPTIONAL */;
	struct VehicleStatus	*item6_72	/* OPTIONAL */;
	struct WiperStatus	*item6_73	/* OPTIONAL */;
	Acceleration_t	*item7_1	/* OPTIONAL */;
	AccelerationConfidence_t	*item7_2	/* OPTIONAL */;
	AmbientAirPressure_t	*item7_3	/* OPTIONAL */;
	AmbientAirTemperature_t	*item7_4	/* OPTIONAL */;
	AntiLockBrakeStatus_t	*item7_5	/* OPTIONAL */;
	ApproachNumber_t	*item7_6	/* OPTIONAL */;
	AuxiliaryBrakeStatus_t	*item7_7	/* OPTIONAL */;
	BarrierAttributes_t	*item7_8	/* OPTIONAL */;
	BrakeAppliedPressure_t	*item7_9	/* OPTIONAL */;
	BrakeAppliedStatus_t	*item7_10	/* OPTIONAL */;
	BrakeBoostApplied_t	*item7_11	/* OPTIONAL */;
	BumperHeightFront_t	*item7_12	/* OPTIONAL */;
	BumperHeightRear_t	*item7_13	/* OPTIONAL */;
	CodeWord_t	*item7_14	/* OPTIONAL */;
	CoefficientOfFriction_t	*item7_15	/* OPTIONAL */;
	ColorState_t	*item7_16	/* OPTIONAL */;
	Count_t	*item7_17	/* OPTIONAL */;
	CrosswalkLaneAttributes_t	*item7_18	/* OPTIONAL */;
	DDay_t	*item7_19	/* OPTIONAL */;
	DescriptiveName_t	*item7_20	/* OPTIONAL */;
	DHour_t	*item7_21	/* OPTIONAL */;
	DirectionOfUse_t	*item7_22	/* OPTIONAL */;
	DMinute_t	*item7_23	/* OPTIONAL */;
	DMonth_t	*item7_24	/* OPTIONAL */;
	DOffset_t	*item7_25	/* OPTIONAL */;
	DrivenLineOffset_t	*item7_26	/* OPTIONAL */;
	DrivingWheelAngle_t	*item7_27	/* OPTIONAL */;
	DSecond_t	*item7_28	/* OPTIONAL */;
	DSignalSeconds_t	*item7_29	/* OPTIONAL */;
	DSRCmsgID_t	*item7_30	/* OPTIONAL */;
	DYear_t	*item7_31	/* OPTIONAL */;
	ElevationConfidence_t	*item7_32	/* OPTIONAL */;
	Elevation_t	*item7_33	/* OPTIONAL */;
	EmergencyDetails_t	*item7_34	/* OPTIONAL */;
	EventFlags_t	*item7_35	/* OPTIONAL */;
	Extent_t	*item7_36	/* OPTIONAL */;
	ExteriorLights_t	*item7_37	/* OPTIONAL */;
	FurtherInfoID_t	*item7_38	/* OPTIONAL */;
	GPSstatus_t	*item7_39	/* OPTIONAL */;
	HeadingConfidence_t	*item7_40	/* OPTIONAL */;
	Heading_t	*item7_41	/* OPTIONAL */;
	HeadingSlice_t	*item7_42	/* OPTIONAL */;
	IntersectionStatusObject_t	*item7_43	/* OPTIONAL */;
	IntersectionID_t	*item7_44	/* OPTIONAL */;
	AxleLocation_t	*item7_45	/* OPTIONAL */;
	AxleWeight_t	*item7_46	/* OPTIONAL */;
	CargoWeight_t	*item7_47	/* OPTIONAL */;
	DriveAxleLiftAirPressure_t	*item7_48	/* OPTIONAL */;
	DriveAxleLocation_t	*item7_49	/* OPTIONAL */;
	DriveAxleLubePressure_t	*item7_50	/* OPTIONAL */;
	DriveAxleTemperature_t	*item7_51	/* OPTIONAL */;
	SteeringAxleLubePressure_t	*item7_52	/* OPTIONAL */;
	SteeringAxleTemperature_t	*item7_53	/* OPTIONAL */;
	TireLeakageRate_t	*item7_54	/* OPTIONAL */;
	TireLocation_t	*item7_55	/* OPTIONAL */;
	TirePressureThresholdDetection_t	*item7_56	/* OPTIONAL */;
	TirePressure_t	*item7_57	/* OPTIONAL */;
	TireTemp_t	*item7_58	/* OPTIONAL */;
	TrailerWeight_t	*item7_59	/* OPTIONAL */;
	WheelEndElectFault_t	*item7_60	/* OPTIONAL */;
	WheelSensorStatus_t	*item7_61	/* OPTIONAL */;
	LaneCount_t	*item7_62	/* OPTIONAL */;
	LaneManeuverCode_t	*item7_63	/* OPTIONAL */;
	LaneNumber_t	*item7_64	/* OPTIONAL */;
	LaneSet_t	*item7_65	/* OPTIONAL */;
	LaneWidth_t	*item7_66	/* OPTIONAL */;
	Latitude_t	*item7_67	/* OPTIONAL */;
	LayerID_t	*item7_68	/* OPTIONAL */;
	LayerType_t	*item7_69	/* OPTIONAL */;
	LightbarInUse_t	*item7_70	/* OPTIONAL */;
	Longitude_t	*item7_71	/* OPTIONAL */;
	Location_quality_t	*item7_72	/* OPTIONAL */;
	Location_tech_t	*item7_73	/* OPTIONAL */;
	MinuteOfTheYear_t	*item7_74	/* OPTIONAL */;
	MinutesDuration_t	*item7_75	/* OPTIONAL */;
	MsgCount_t	*item7_76	/* OPTIONAL */;
	MsgCRC_t	*item7_77	/* OPTIONAL */;
	MultiVehicleResponse_t	*item7_78	/* OPTIONAL */;
	MUTCDCode_t	*item7_79	/* OPTIONAL */;
	NMEA_MsgType_t	*item7_80	/* OPTIONAL */;
	NMEA_Payload_t	*item7_81	/* OPTIONAL */;
	NMEA_Revision_t	*item7_82	/* OPTIONAL */;
	NTCIPVehicleclass_t	*item7_83	/* OPTIONAL */;
	ObjectCount_t	*item7_84	/* OPTIONAL */;
	ObstacleDirection_t	*item7_85	/* OPTIONAL */;
	ObstacleDistance_t	*item7_86	/* OPTIONAL */;
	PayloadData_t	*item7_87	/* OPTIONAL */;
	Payload_t	*item7_88	/* OPTIONAL */;
	PedestrianDetect_t	*item7_89	/* OPTIONAL */;
	PedestrianSignalState_t	*item7_90	/* OPTIONAL */;
	PositionConfidence_t	*item7_91	/* OPTIONAL */;
	PreemptState_t	*item7_92	/* OPTIONAL */;
	Priority_t	*item7_93	/* OPTIONAL */;
	PriorityState_t	*item7_94	/* OPTIONAL */;
	ProbeSegmentNumber_t	*item7_95	/* OPTIONAL */;
	RainSensor_t	*item7_96	/* OPTIONAL */;
	RequestedItem_t	*item7_97	/* OPTIONAL */;
	ResponseType_t	*item7_98	/* OPTIONAL */;
	RTCM_ID_t	*item7_99	/* OPTIONAL */;
	RTCM_Payload_t	*item7_100	/* OPTIONAL */;
	RTCM_Revision_t	*item7_101	/* OPTIONAL */;
	SignalLightState_t	*item7_102	/* OPTIONAL */;
	SignalReqScheme_t	*item7_103	/* OPTIONAL */;
	SignalState_t	*item7_104	/* OPTIONAL */;
	SignPrority_t	*item7_105	/* OPTIONAL */;
	SirenInUse_t	*item7_106	/* OPTIONAL */;
	SpecialLaneAttributes_t	*item7_107	/* OPTIONAL */;
	SpecialSignalState_t	*item7_108	/* OPTIONAL */;
	SpeedConfidence_t	*item7_109	/* OPTIONAL */;
	Speed_t	*item7_110	/* OPTIONAL */;
	StabilityControlStatus_t	*item7_111	/* OPTIONAL */;
	StateConfidence_t	*item7_112	/* OPTIONAL */;
	SteeringWheelAngleConfidence_t	*item7_113	/* OPTIONAL */;
	SteeringWheelAngleRateOfChange_t	*item7_114	/* OPTIONAL */;
	SteeringWheelAngle_t	*item7_115	/* OPTIONAL */;
	SunSensor_t	*item7_116	/* OPTIONAL */;
	TemporaryID_t	*item7_117	/* OPTIONAL */;
	TermDistance_t	*item7_118	/* OPTIONAL */;
	TermTime_t	*item7_119	/* OPTIONAL */;
	ThrottleConfidence_t	*item7_120	/* OPTIONAL */;
	ThrottlePosition_t	*item7_121	/* OPTIONAL */;
	TimeConfidence_t	*item7_122	/* OPTIONAL */;
	TimeMark_t	*item7_123	/* OPTIONAL */;
	TractionControlState_t	*item7_124	/* OPTIONAL */;
	TransitPreEmptionRequest_t	*item7_125	/* OPTIONAL */;
	TransitStatus_t	*item7_126	/* OPTIONAL */;
	TransmissionState_t	*item7_127	/* OPTIONAL */;
	TxTime_t	*item7_128	/* OPTIONAL */;
	TravelerInfoType_t	*item7_129	/* OPTIONAL */;
	UniqueMSGID_t	*item7_130	/* OPTIONAL */;
	URL_Base_t	*item7_131	/* OPTIONAL */;
	URL_Link_t	*item7_132	/* OPTIONAL */;
	URL_Short_t	*item7_133	/* OPTIONAL */;
	VehicleHeight_t	*item7_134	/* OPTIONAL */;
	VehicleLaneAttributes_t	*item7_135	/* OPTIONAL */;
	VehicleLength_t	*item7_136	/* OPTIONAL */;
	VehicleMass_t	*item7_137	/* OPTIONAL */;
	VehicleRequestStatus_t	*item7_138	/* OPTIONAL */;
	VehicleStatusDeviceTypeTag_t	*item7_139	/* OPTIONAL */;
	VehicleType_t	*item7_140	/* OPTIONAL */;
	VehicleWidth_t	*item7_141	/* OPTIONAL */;
	VerticalAccelerationThreshold_t	*item7_142	/* OPTIONAL */;
	VerticalAcceleration_t	*item7_143	/* OPTIONAL */;
	VINstring_t	*item7_144	/* OPTIONAL */;
	WiperRate_t	*item7_145	/* OPTIONAL */;
	WiperStatusFront_t	*item7_146	/* OPTIONAL */;
	WiperStatusRear_t	*item7_147	/* OPTIONAL */;
	YawRateConfidence_t	*item7_148	/* OPTIONAL */;
	YawRate_t	*item7_149	/* OPTIONAL */;
	IncidentResponseEquipment_t	*item8_1	/* OPTIONAL */;
	ITIStext_t	*item8_2	/* OPTIONAL */;
	ResponderGroupAffected_t	*item8_3	/* OPTIONAL */;
	VehicleGroupAffected_t	*item8_4	/* OPTIONAL */;
	struct ITIScodesAndText	*item8_5	/* OPTIONAL */;
	EssMobileFriction_t	*item8_6	/* OPTIONAL */;
	EssPrecipRate_t	*item8_7	/* OPTIONAL */;
	EssPrecipSituation_t	*item8_8	/* OPTIONAL */;
	EssPrecipYesNo_t	*item8_9	/* OPTIONAL */;
	EssSolarRadiation_t	*item8_10	/* OPTIONAL */;
	ITIScodes_t	*item8_11	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AllInclusive_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AllInclusive;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/AccelSteerYawRateConfidence.h>
#include <SAE_J2735/Approach.h>
#include <SAE_J2735/ApproachObject.h>
#include <SAE_J2735/BarrierLane.h>
#include <SAE_J2735/BumperHeights.h>
#include <SAE_J2735/Circle.h>
#include <SAE_J2735/ConfidenceSet.h>
#include <SAE_J2735/CrosswalkLane.h>
#include <SAE_J2735/DataParameters.h>
#include <SAE_J2735/DDate.h>
#include <SAE_J2735/DDateTime.h>
#include <SAE_J2735/DFullTime.h>
#include <SAE_J2735/DMonthDay.h>
#include <SAE_J2735/DTime.h>
#include <SAE_J2735/DYearMonth.h>
#include <SAE_J2735/FullPositionVector.h>
#include <SAE_J2735/Intersection.h>
#include <SAE_J2735/IntersectionState.h>
#include <SAE_J2735/ExitService.h>
#include <SAE_J2735/GenericSignage.h>
#include <SAE_J2735/SpeedLimit.h>
#include <SAE_J2735/WorkZone.h>
#include <SAE_J2735/J1939data.h>
#include <SAE_J2735/MovementState.h>
#include <SAE_J2735/NodeList.h>
#include <SAE_J2735/PathHistory.h>
#include <SAE_J2735/PathHistoryPointType-01.h>
#include <SAE_J2735/PathPrediction.h>
#include <SAE_J2735/Position3D.h>
#include <SAE_J2735/RegionList.h>
#include <SAE_J2735/RegionOffsets.h>
#include <SAE_J2735/RegionPointSet.h>
#include <SAE_J2735/RoadSignID.h>
#include <SAE_J2735/RTCMmsg.h>
#include <SAE_J2735/RTCMPackage.h>
#include <SAE_J2735/Sample.h>
#include <SAE_J2735/ShapePointSet.h>
#include <SAE_J2735/SignalControlZone.h>
#include <SAE_J2735/SignalRequest.h>
#include <SAE_J2735/SnapshotDistance.h>
#include <SAE_J2735/Snapshot.h>
#include <SAE_J2735/SnapshotTime.h>
#include <SAE_J2735/SpecialLane.h>
#include <SAE_J2735/ValidRegion.h>
#include <SAE_J2735/VehicleComputedLane.h>
#include <SAE_J2735/VehicleIdent.h>
#include <SAE_J2735/VehicleReferenceLane.h>
#include <SAE_J2735/VehicleSafetyExtension.h>
#include <SAE_J2735/VehicleSize.h>
#include <SAE_J2735/VehicleStatusRequest.h>
#include <SAE_J2735/VehicleStatus.h>
#include <SAE_J2735/WiperStatus.h>
#include <SAE_J2735/ITIScodesAndText.h>

#endif	/* _AllInclusive_H_ */
#include <SAE_J2735/asn_internal.h>
