/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_AlaCarte_H_
#define	_AlaCarte_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include "AllInclusive.h"
#include <SAE_J2735/MsgCRC.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlaCarte */
typedef struct AlaCarte {
	DSRCmsgID_t	 msgID;
	AllInclusive_t	 data;
	MsgCRC_t	*crc	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlaCarte_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlaCarte;

#ifdef __cplusplus
}
#endif

#endif	/* _AlaCarte_H_ */
#include <SAE_J2735/asn_internal.h>
