/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_AntiLockBrakeStatus_H_
#define	_AntiLockBrakeStatus_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AntiLockBrakeStatus {
	AntiLockBrakeStatus_unavailable	= 0,
	AntiLockBrakeStatus_off	= 1,
	AntiLockBrakeStatus_on	= 2,
	AntiLockBrakeStatus_engaged	= 3
} e_AntiLockBrakeStatus;

/* AntiLockBrakeStatus */
typedef long	 AntiLockBrakeStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AntiLockBrakeStatus;
asn_struct_free_f AntiLockBrakeStatus_free;
asn_struct_print_f AntiLockBrakeStatus_print;
asn_constr_check_f AntiLockBrakeStatus_constraint;
ber_type_decoder_f AntiLockBrakeStatus_decode_ber;
der_type_encoder_f AntiLockBrakeStatus_encode_der;
xer_type_decoder_f AntiLockBrakeStatus_decode_xer;
xer_type_encoder_f AntiLockBrakeStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AntiLockBrakeStatus_H_ */
#include <SAE_J2735/asn_internal.h>
