/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_BarrierLane_H_
#define	_BarrierLane_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/LaneNumber.h>
#include <SAE_J2735/LaneWidth.h>
#include <SAE_J2735/BarrierAttributes.h>
#include <SAE_J2735/NodeList.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BarrierLane */
typedef struct BarrierLane {
	LaneNumber_t	 laneNumber;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	BarrierAttributes_t	 barrierAttributes;
	NodeList_t	 nodeList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BarrierLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BarrierLane;

#ifdef __cplusplus
}
#endif

#endif	/* _BarrierLane_H_ */
#include <SAE_J2735/asn_internal.h>
