/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_BasicSafetyMessageVerbose_H_
#define	_BasicSafetyMessageVerbose_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/MsgCount.h>
#include <SAE_J2735/TemporaryID.h>
#include <SAE_J2735/DSecond.h>
#include <SAE_J2735/Latitude.h>
#include <SAE_J2735/Longitude.h>
#include <SAE_J2735/Elevation.h>
#include <SAE_J2735/PositionalAccuracy.h>
#include <SAE_J2735/TransmissionAndSpeed.h>
#include <SAE_J2735/Heading.h>
#include <SAE_J2735/SteeringWheelAngle.h>
#include <SAE_J2735/AccelerationSet4Way.h>
#include <SAE_J2735/BrakeSystemStatus.h>
#include <SAE_J2735/VehicleSize.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleSafetyExtension;
struct VehicleStatus;

/* BasicSafetyMessageVerbose */
typedef struct BasicSafetyMessageVerbose {
	DSRCmsgID_t	 msgID;
	MsgCount_t	 msgCnt;
	TemporaryID_t	 id;
	DSecond_t	 secMark;
	Latitude_t	 lat;
	Longitude_t	 Long;
	Elevation_t	 elev;
	PositionalAccuracy_t	 accuracy;
	TransmissionAndSpeed_t	 speed;
	Heading_t	 heading;
	SteeringWheelAngle_t	 angle;
	AccelerationSet4Way_t	 accelSet;
	BrakeSystemStatus_t	 brakes;
	VehicleSize_t	 size;
	struct VehicleSafetyExtension	*safetyExt	/* OPTIONAL */;
	struct VehicleStatus	*status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicSafetyMessageVerbose_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicSafetyMessageVerbose;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/VehicleSafetyExtension.h>
#include <SAE_J2735/VehicleStatus.h>

#endif	/* _BasicSafetyMessageVerbose_H_ */
#include <SAE_J2735/asn_internal.h>
