/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_BasicSafetyMessage_H_
#define	_BasicSafetyMessage_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/BSMblob.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleSafetyExtension;
struct VehicleStatus;

/* BasicSafetyMessage */
typedef struct BasicSafetyMessage {
	DSRCmsgID_t	 msgID;
	BSMblob_t	 blob1;
	struct VehicleSafetyExtension	*safetyExt	/* OPTIONAL */;
	struct VehicleStatus	*status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicSafetyMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicSafetyMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/VehicleSafetyExtension.h>
#include <SAE_J2735/VehicleStatus.h>

#endif	/* _BasicSafetyMessage_H_ */
#include <SAE_J2735/asn_internal.h>
