/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_Circle_H_
#define	_Circle_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/Position3D.h>
#include <SAE_J2735/NativeInteger.h>
#include <SAE_J2735/constr_CHOICE.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum raduis_PR {
	raduis_PR_NOTHING,	/* No components present */
	raduis_PR_radiusSteps,
	raduis_PR_miles,
	raduis_PR_km
} raduis_PR;

/* Circle */
typedef struct Circle {
	Position3D_t	 center;
	struct raduis {
		raduis_PR present;
		union Circle__raduis_u {
			long	 radiusSteps;
			long	 miles;
			long	 km;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} raduis;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Circle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Circle;

#ifdef __cplusplus
}
#endif

#endif	/* _Circle_H_ */
#include <SAE_J2735/asn_internal.h>
