/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_CommonSafetyRequest_H_
#define	_CommonSafetyRequest_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/MsgCount.h>
#include <SAE_J2735/TemporaryID.h>
#include <SAE_J2735/RequestedItem.h>
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CommonSafetyRequest */
typedef struct CommonSafetyRequest {
	DSRCmsgID_t	 msgID;
	MsgCount_t	*msgCnt	/* OPTIONAL */;
	TemporaryID_t	*id	/* OPTIONAL */;
	struct requests {
		A_SEQUENCE_OF(RequestedItem_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} requests;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CommonSafetyRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CommonSafetyRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _CommonSafetyRequest_H_ */
#include <SAE_J2735/asn_internal.h>
