/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_DDate_H_
#define	_DDate_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DYear.h>
#include <SAE_J2735/DMonth.h>
#include <SAE_J2735/DDay.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DDate */
typedef struct DDate {
	DYear_t	 year;
	DMonth_t	 month;
	DDay_t	 day;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DDate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DDate;

#ifdef __cplusplus
}
#endif

#endif	/* _DDate_H_ */
#include <SAE_J2735/asn_internal.h>
