/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_DFullTime_H_
#define	_DFullTime_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DYear.h>
#include <SAE_J2735/DMonth.h>
#include <SAE_J2735/DDay.h>
#include <SAE_J2735/DHour.h>
#include <SAE_J2735/DMinute.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DFullTime */
typedef struct DFullTime {
	DYear_t	 year;
	DMonth_t	 month;
	DDay_t	 day;
	DHour_t	 hour;
	DMinute_t	 minute;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DFullTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DFullTime;

#ifdef __cplusplus
}
#endif

#endif	/* _DFullTime_H_ */
#include <SAE_J2735/asn_internal.h>
