/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_DOffset_H_
#define	_DOffset_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DOffset */
typedef long	 DOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DOffset;
asn_struct_free_f DOffset_free;
asn_struct_print_f DOffset_print;
asn_constr_check_f DOffset_constraint;
ber_type_decoder_f DOffset_decode_ber;
der_type_encoder_f DOffset_encode_der;
xer_type_decoder_f DOffset_decode_xer;
xer_type_encoder_f DOffset_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DOffset_H_ */
#include <SAE_J2735/asn_internal.h>
