/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_EmergencyVehicleAlert_H_
#define	_EmergencyVehicleAlert_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/TemporaryID.h>
#include <SAE_J2735/RoadSideAlert.h>
#include <SAE_J2735/ResponseType.h>
#include <SAE_J2735/EmergencyDetails.h>
#include <SAE_J2735/VehicleMass.h>
#include <SAE_J2735/VehicleType.h>
#include <SAE_J2735/VehicleGroupAffected.h>
#include <SAE_J2735/IncidentResponseEquipment.h>
#include <SAE_J2735/ResponderGroupAffected.h>
#include <SAE_J2735/MsgCRC.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EmergencyVehicleAlert */
typedef struct EmergencyVehicleAlert {
	DSRCmsgID_t	 msgID;
	TemporaryID_t	*id	/* OPTIONAL */;
	RoadSideAlert_t	 rsaMsg;
	ResponseType_t	*responseType	/* OPTIONAL */;
	EmergencyDetails_t	*details	/* OPTIONAL */;
	VehicleMass_t	*mass	/* OPTIONAL */;
	VehicleType_t	*basicType	/* OPTIONAL */;
	VehicleGroupAffected_t	*vehicleType	/* OPTIONAL */;
	IncidentResponseEquipment_t	*responseEquip	/* OPTIONAL */;
	ResponderGroupAffected_t	*responderType	/* OPTIONAL */;
	MsgCRC_t	 crc;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EmergencyVehicleAlert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EmergencyVehicleAlert;

#ifdef __cplusplus
}
#endif

#endif	/* _EmergencyVehicleAlert_H_ */
#include <SAE_J2735/asn_internal.h>
