/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "NTCIP"
 * 	found in "J2735.asn"
 */

#ifndef	_EssMobileFriction_H_
#define	_EssMobileFriction_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EssMobileFriction */
typedef long	 EssMobileFriction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EssMobileFriction;
asn_struct_free_f EssMobileFriction_free;
asn_struct_print_f EssMobileFriction_print;
asn_constr_check_f EssMobileFriction_constraint;
ber_type_decoder_f EssMobileFriction_decode_ber;
der_type_encoder_f EssMobileFriction_encode_der;
xer_type_decoder_f EssMobileFriction_decode_xer;
xer_type_encoder_f EssMobileFriction_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EssMobileFriction_H_ */
#include <SAE_J2735/asn_internal.h>
