/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "NTCIP"
 * 	found in "J2735.asn"
 */

#ifndef	_EssSolarRadiation_H_
#define	_EssSolarRadiation_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EssSolarRadiation */
typedef long	 EssSolarRadiation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EssSolarRadiation;
asn_struct_free_f EssSolarRadiation_free;
asn_struct_print_f EssSolarRadiation_print;
asn_constr_check_f EssSolarRadiation_constraint;
ber_type_decoder_f EssSolarRadiation_decode_ber;
der_type_encoder_f EssSolarRadiation_encode_der;
xer_type_decoder_f EssSolarRadiation_decode_xer;
xer_type_encoder_f EssSolarRadiation_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EssSolarRadiation_H_ */
#include <SAE_J2735/asn_internal.h>
