/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_EventFlags_H_
#define	_EventFlags_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EventFlags */
typedef long	 EventFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventFlags;
asn_struct_free_f EventFlags_free;
asn_struct_print_f EventFlags_print;
asn_constr_check_f EventFlags_constraint;
ber_type_decoder_f EventFlags_decode_ber;
der_type_encoder_f EventFlags_encode_der;
xer_type_decoder_f EventFlags_decode_xer;
xer_type_encoder_f EventFlags_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EventFlags_H_ */
#include <SAE_J2735/asn_internal.h>
