/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_ExitService_H_
#define	_ExitService_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/ITIScodes.h>
#include <SAE_J2735/IA5String.h>
#include <SAE_J2735/constr_CHOICE.h>
#include <SAE_J2735/constr_SEQUENCE.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum item4_PR {
	item4_PR_NOTHING,	/* No components present */
	item4_PR_itis4,
	item4_PR_text4
} item4_PR;

/* ExitService */
typedef struct ExitService {
	A_SEQUENCE_OF(struct Member5 {
		struct item4 {
			item4_PR present;
			union item4_u {
				ITIScodes_t	 itis4;
				IA5String_t	 text4;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} item4;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExitService_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExitService;

#ifdef __cplusplus
}
#endif

#endif	/* _ExitService_H_ */
#include <SAE_J2735/asn_internal.h>
