/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_FullPositionVector_H_
#define	_FullPositionVector_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/Longitude.h>
#include <SAE_J2735/Latitude.h>
#include <SAE_J2735/Elevation.h>
#include <SAE_J2735/Heading.h>
#include <SAE_J2735/TransmissionAndSpeed.h>
#include <SAE_J2735/PositionalAccuracy.h>
#include <SAE_J2735/TimeConfidence.h>
#include <SAE_J2735/PositionConfidenceSet.h>
#include <SAE_J2735/SpeedandHeadingandThrottleConfidence.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DDateTime;

/* FullPositionVector */
typedef struct FullPositionVector {
	struct DDateTime	*utcTime	/* OPTIONAL */;
	Longitude_t	 Long;
	Latitude_t	 lat;
	Elevation_t	*elevation	/* OPTIONAL */;
	Heading_t	*heading	/* OPTIONAL */;
	TransmissionAndSpeed_t	*speed	/* OPTIONAL */;
	PositionalAccuracy_t	*posAccuracy	/* OPTIONAL */;
	TimeConfidence_t	*timeConfidence	/* OPTIONAL */;
	PositionConfidenceSet_t	*posConfidence	/* OPTIONAL */;
	SpeedandHeadingandThrottleConfidence_t	*speedConfidence	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FullPositionVector_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FullPositionVector;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/DDateTime.h>

#endif	/* _FullPositionVector_H_ */
#include <SAE_J2735/asn_internal.h>
