/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_GenericSignage_H_
#define	_GenericSignage_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/ITIScodes.h>
#include <SAE_J2735/IA5String.h>
#include <SAE_J2735/constr_CHOICE.h>
#include <SAE_J2735/constr_SEQUENCE.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum item2_PR {
	item2_PR_NOTHING,	/* No components present */
	item2_PR_itis2,
	item2_PR_text2
} item2_PR;

/* GenericSignage */
typedef struct GenericSignage {
	A_SEQUENCE_OF(struct Member3 {
		struct item2 {
			item2_PR present;
			union item2_u {
				ITIScodes_t	 itis2;
				IA5String_t	 text2;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} item2;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GenericSignage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GenericSignage;

#ifdef __cplusplus
}
#endif

#endif	/* _GenericSignage_H_ */
#include <SAE_J2735/asn_internal.h>
