/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_HeadingSlice_H_
#define	_HeadingSlice_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HeadingSlice */
typedef OCTET_STRING_t	 HeadingSlice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HeadingSlice;
asn_struct_free_f HeadingSlice_free;
asn_struct_print_f HeadingSlice_print;
asn_constr_check_f HeadingSlice_constraint;
ber_type_decoder_f HeadingSlice_decode_ber;
der_type_encoder_f HeadingSlice_encode_der;
xer_type_decoder_f HeadingSlice_decode_xer;
xer_type_encoder_f HeadingSlice_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HeadingSlice_H_ */
#include <SAE_J2735/asn_internal.h>
