/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_Intersection_H_
#define	_Intersection_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DescriptiveName.h>
#include <SAE_J2735/IntersectionID.h>
#include <SAE_J2735/Heading.h>
#include <SAE_J2735/LaneWidth.h>
#include <SAE_J2735/IntersectionStatusObject.h>
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Position3D;
struct ApproachObject;
struct SignalControlZone;

/* Intersection */
typedef struct Intersection {
	DescriptiveName_t	*name	/* OPTIONAL */;
	IntersectionID_t	 id;
	struct Position3D	*refPoint	/* OPTIONAL */;
	IntersectionID_t	*refInterNum	/* OPTIONAL */;
	Heading_t	*orientation	/* OPTIONAL */;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	IntersectionStatusObject_t	*type	/* OPTIONAL */;
	struct approaches {
		A_SEQUENCE_OF(struct ApproachObject) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} approaches;
	struct preemptZones {
		A_SEQUENCE_OF(struct SignalControlZone) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *preemptZones;
	struct priorityZones {
		A_SEQUENCE_OF(struct SignalControlZone) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *priorityZones;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Intersection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Intersection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/Position3D.h>
#include <SAE_J2735/ApproachObject.h>
#include <SAE_J2735/SignalControlZone.h>

#endif	/* _Intersection_H_ */
#include <SAE_J2735/asn_internal.h>
