/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_IntersectionCollision_H_
#define	_IntersectionCollision_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/MsgCount.h>
#include <SAE_J2735/TemporaryID.h>
#include <SAE_J2735/DSecond.h>
#include <SAE_J2735/PathHistory.h>
#include <SAE_J2735/IntersectionID.h>
#include <SAE_J2735/LaneNumber.h>
#include <SAE_J2735/EventFlags.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntersectionCollision */
typedef struct IntersectionCollision {
	DSRCmsgID_t	 msgID;
	MsgCount_t	 msgCnt;
	TemporaryID_t	 id;
	DSecond_t	*secMark	/* OPTIONAL */;
	PathHistory_t	 path;
	IntersectionID_t	 intersetionID;
	LaneNumber_t	 laneNumber;
	EventFlags_t	 eventFlag;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionCollision_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionCollision;

#ifdef __cplusplus
}
#endif

#endif	/* _IntersectionCollision_H_ */
#include <SAE_J2735/asn_internal.h>
