/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ITIS"
 * 	found in "J2735.asn"
 */

#ifndef	_ITIScodesAndText_H_
#define	_ITIScodesAndText_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/ITIScodes.h>
#include <SAE_J2735/ITIStext.h>
#include <SAE_J2735/constr_CHOICE.h>
#include <SAE_J2735/constr_SEQUENCE.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum item_PR {
	item_PR_NOTHING,	/* No components present */
	item_PR_itis,
	item_PR_text
} item_PR;

/* ITIScodesAndText */
typedef struct ITIScodesAndText {
	A_SEQUENCE_OF(struct Member7 {
		struct item {
			item_PR present;
			union item_u {
				ITIScodes_t	 itis;
				ITIStext_t	 text;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} item;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ITIScodesAndText_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ITIScodesAndText;

#ifdef __cplusplus
}
#endif

#endif	/* _ITIScodesAndText_H_ */
#include <SAE_J2735/asn_internal.h>
