/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ITIS"
 * 	found in "J2735.asn"
 */

#ifndef	_ITIScodes_H_
#define	_ITIScodes_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ITIScodes */
typedef long	 ITIScodes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ITIScodes;
asn_struct_free_f ITIScodes_free;
asn_struct_print_f ITIScodes_print;
asn_constr_check_f ITIScodes_constraint;
ber_type_decoder_f ITIScodes_decode_ber;
der_type_encoder_f ITIScodes_encode_der;
xer_type_decoder_f ITIScodes_decode_xer;
xer_type_encoder_f ITIScodes_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ITIScodes_H_ */
#include <SAE_J2735/asn_internal.h>
