/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_J1939data_H_
#define	_J1939data_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/TrailerWeight.h>
#include <SAE_J2735/CargoWeight.h>
#include <SAE_J2735/SteeringAxleTemperature.h>
#include <SAE_J2735/DriveAxleLocation.h>
#include <SAE_J2735/DriveAxleLiftAirPressure.h>
#include <SAE_J2735/DriveAxleTemperature.h>
#include <SAE_J2735/DriveAxleLubePressure.h>
#include <SAE_J2735/SteeringAxleLubePressure.h>
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/TireLocation.h>
#include <SAE_J2735/TirePressure.h>
#include <SAE_J2735/TireTemp.h>
#include <SAE_J2735/WheelSensorStatus.h>
#include <SAE_J2735/WheelEndElectFault.h>
#include <SAE_J2735/TireLeakageRate.h>
#include <SAE_J2735/TirePressureThresholdDetection.h>
#include <SAE_J2735/constr_SEQUENCE.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>
#include <SAE_J2735/AxleLocation.h>
#include <SAE_J2735/AxleWeight.h>

#ifdef __cplusplus
extern "C" {
#endif

/* J1939data */
typedef struct J1939data {
	struct tires {
		A_SEQUENCE_OF(struct Member6 {
			TireLocation_t	*location	/* OPTIONAL */;
			TirePressure_t	*pressure	/* OPTIONAL */;
			TireTemp_t	*temp	/* OPTIONAL */;
			WheelSensorStatus_t	*wheelSensorStatus	/* OPTIONAL */;
			WheelEndElectFault_t	*wheelEndElectFault	/* OPTIONAL */;
			TireLeakageRate_t	*leakageRate	/* OPTIONAL */;
			TirePressureThresholdDetection_t	*detection	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tires;
	struct axle {
		A_SEQUENCE_OF(struct Member66 {
			AxleLocation_t	*location	/* OPTIONAL */;
			AxleWeight_t	*weight	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *axle;
	TrailerWeight_t	*trailerWeight	/* OPTIONAL */;
	CargoWeight_t	*cargoWeight	/* OPTIONAL */;
	SteeringAxleTemperature_t	*steeringAxleTemperature	/* OPTIONAL */;
	DriveAxleLocation_t	*driveAxleLocation	/* OPTIONAL */;
	DriveAxleLiftAirPressure_t	*driveAxleLiftAirPressure	/* OPTIONAL */;
	DriveAxleTemperature_t	*driveAxleTemperature	/* OPTIONAL */;
	DriveAxleLubePressure_t	*driveAxleLubePressure	/* OPTIONAL */;
	SteeringAxleLubePressure_t	*steeringAxleLubePressure	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} J1939data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_J1939data;

#ifdef __cplusplus
}
#endif

#endif	/* _J1939data_H_ */
#include <SAE_J2735/asn_internal.h>
