/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_LaneWidth_H_
#define	_LaneWidth_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LaneWidth */
typedef long	 LaneWidth_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneWidth;
asn_struct_free_f LaneWidth_free;
asn_struct_print_f LaneWidth_print;
asn_constr_check_f LaneWidth_constraint;
ber_type_decoder_f LaneWidth_decode_ber;
der_type_encoder_f LaneWidth_encode_der;
xer_type_decoder_f LaneWidth_decode_xer;
xer_type_encoder_f LaneWidth_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LaneWidth_H_ */
#include <SAE_J2735/asn_internal.h>
