/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_MinuteOfTheYear_H_
#define	_MinuteOfTheYear_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MinuteOfTheYear */
typedef long	 MinuteOfTheYear_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MinuteOfTheYear;
asn_struct_free_f MinuteOfTheYear_free;
asn_struct_print_f MinuteOfTheYear_print;
asn_constr_check_f MinuteOfTheYear_constraint;
ber_type_decoder_f MinuteOfTheYear_decode_ber;
der_type_encoder_f MinuteOfTheYear_encode_der;
xer_type_decoder_f MinuteOfTheYear_decode_xer;
xer_type_encoder_f MinuteOfTheYear_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MinuteOfTheYear_H_ */
#include <SAE_J2735/asn_internal.h>
