/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_MsgCount_H_
#define	_MsgCount_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MsgCount */
typedef long	 MsgCount_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsgCount;
asn_struct_free_f MsgCount_free;
asn_struct_print_f MsgCount_print;
asn_constr_check_f MsgCount_constraint;
ber_type_decoder_f MsgCount_decode_ber;
der_type_encoder_f MsgCount_encode_der;
xer_type_decoder_f MsgCount_decode_xer;
xer_type_encoder_f MsgCount_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MsgCount_H_ */
#include <SAE_J2735/asn_internal.h>
