/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_NMEA_Corrections_H_
#define	_NMEA_Corrections_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/NMEA-Revision.h>
#include <SAE_J2735/NMEA-MsgType.h>
#include <SAE_J2735/NativeInteger.h>
#include <SAE_J2735/NMEA-Payload.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NMEA-Corrections */
typedef struct NMEA_Corrections {
	DSRCmsgID_t	 msgID;
	NMEA_Revision_t	 rev;
	NMEA_MsgType_t	 msg;
	long	 wdCount;
	NMEA_Payload_t	 payload;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NMEA_Corrections_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NMEA_Corrections;

#ifdef __cplusplus
}
#endif

#endif	/* _NMEA_Corrections_H_ */
#include <SAE_J2735/asn_internal.h>
