/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_NMEA_Payload_H_
#define	_NMEA_Payload_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NMEA-Payload */
typedef OCTET_STRING_t	 NMEA_Payload_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NMEA_Payload;
asn_struct_free_f NMEA_Payload_free;
asn_struct_print_f NMEA_Payload_print;
asn_constr_check_f NMEA_Payload_constraint;
ber_type_decoder_f NMEA_Payload_decode_ber;
der_type_encoder_f NMEA_Payload_encode_der;
xer_type_decoder_f NMEA_Payload_decode_xer;
xer_type_encoder_f NMEA_Payload_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NMEA_Payload_H_ */
#include <SAE_J2735/asn_internal.h>
