/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_NMEA_MsgType_H_
#define	_NMEA_MsgType_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NMEA-MsgType */
typedef long	 NMEA_MsgType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NMEA_MsgType;
asn_struct_free_f NMEA_MsgType_free;
asn_struct_print_f NMEA_MsgType_print;
asn_constr_check_f NMEA_MsgType_constraint;
ber_type_decoder_f NMEA_MsgType_decode_ber;
der_type_encoder_f NMEA_MsgType_encode_der;
xer_type_decoder_f NMEA_MsgType_decode_xer;
xer_type_encoder_f NMEA_MsgType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _NMEA_MsgType_H_ */
#include <SAE_J2735/asn_internal.h>
