/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_NodeList_H_
#define	_NodeList_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/Offsets.h>
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NodeList */
typedef struct NodeList {
	A_SEQUENCE_OF(Offsets_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeList;

#ifdef __cplusplus
}
#endif

#endif	/* _NodeList_H_ */
#include <SAE_J2735/asn_internal.h>
