/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_Offsets_H_
#define	_Offsets_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Offsets */
typedef OCTET_STRING_t	 Offsets_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Offsets;
asn_struct_free_f Offsets_free;
asn_struct_print_f Offsets_print;
asn_constr_check_f Offsets_constraint;
ber_type_decoder_f Offsets_decode_ber;
der_type_encoder_f Offsets_encode_der;
xer_type_decoder_f Offsets_decode_xer;
xer_type_encoder_f Offsets_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Offsets_H_ */
#include <SAE_J2735/asn_internal.h>
