/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_PathHistoryPointType_01_H_
#define	_PathHistoryPointType_01_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>
#include <SAE_J2735/PositionalAccuracy.h>
#include <SAE_J2735/TransmissionAndSpeed.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PathHistoryPointType-01 */
typedef struct PathHistoryPointType_01 {
	long	 latOffset;
	long	 longOffset;
	long	*elevationOffset	/* OPTIONAL */;
	long	*timeOffset	/* OPTIONAL */;
	PositionalAccuracy_t	*posAccuracy	/* OPTIONAL */;
	long	*heading	/* OPTIONAL */;
	TransmissionAndSpeed_t	*speed	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathHistoryPointType_01_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathHistoryPointType_01;

#ifdef __cplusplus
}
#endif

#endif	/* _PathHistoryPointType_01_H_ */
#include <SAE_J2735/asn_internal.h>
