/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_PathHistoryPointType_03_H_
#define	_PathHistoryPointType_03_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PathHistoryPointType-03 */
typedef OCTET_STRING_t	 PathHistoryPointType_03_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathHistoryPointType_03;
asn_struct_free_f PathHistoryPointType_03_free;
asn_struct_print_f PathHistoryPointType_03_print;
asn_constr_check_f PathHistoryPointType_03_constraint;
ber_type_decoder_f PathHistoryPointType_03_decode_ber;
der_type_encoder_f PathHistoryPointType_03_encode_der;
xer_type_decoder_f PathHistoryPointType_03_decode_xer;
xer_type_encoder_f PathHistoryPointType_03_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PathHistoryPointType_03_H_ */
#include <SAE_J2735/asn_internal.h>
