/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_ProbeDataManagement_H_
#define	_ProbeDataManagement_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/Sample.h>
#include <SAE_J2735/HeadingSlice.h>
#include <SAE_J2735/TxTime.h>
#include <SAE_J2735/Count.h>
#include <SAE_J2735/TermTime.h>
#include <SAE_J2735/TermDistance.h>
#include <SAE_J2735/constr_CHOICE.h>
#include <SAE_J2735/SnapshotTime.h>
#include <SAE_J2735/SnapshotDistance.h>
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum term_PR {
	term_PR_NOTHING,	/* No components present */
	term_PR_termtime,
	term_PR_termDistance
} term_PR;
typedef enum snapshot_PR {
	snapshot_PR_NOTHING,	/* No components present */
	snapshot_PR_snapshotTime,
	snapshot_PR_snapshotDistance
} snapshot_PR;

/* Forward declarations */
struct VehicleStatusRequest;

/* ProbeDataManagement */
typedef struct ProbeDataManagement {
	DSRCmsgID_t	 msgID;
	Sample_t	 sample;
	HeadingSlice_t	 directions;
	struct term {
		term_PR present;
		union ProbeDataManagement__term_u {
			TermTime_t	 termtime;
			TermDistance_t	 termDistance;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} term;
	struct snapshot {
		snapshot_PR present;
		union ProbeDataManagement__snapshot_u {
			SnapshotTime_t	 snapshotTime;
			SnapshotDistance_t	 snapshotDistance;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} snapshot;
	TxTime_t	 txInterval;
	Count_t	 cntTthreshold;
	struct dataElements {
		A_SEQUENCE_OF(struct VehicleStatusRequest) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dataElements;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProbeDataManagement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProbeDataManagement;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/VehicleStatusRequest.h>

#endif	/* _ProbeDataManagement_H_ */
#include <SAE_J2735/asn_internal.h>
