/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_ProbeVehicleData_H_
#define	_ProbeVehicleData_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/ProbeSegmentNumber.h>
#include <SAE_J2735/FullPositionVector.h>
#include <SAE_J2735/VehicleType.h>
#include <SAE_J2735/Count.h>
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleIdent;
struct Snapshot;

/* ProbeVehicleData */
typedef struct ProbeVehicleData {
	DSRCmsgID_t	 msgID;
	ProbeSegmentNumber_t	*segNum	/* OPTIONAL */;
	struct VehicleIdent	*probeID	/* OPTIONAL */;
	FullPositionVector_t	 startVector;
	VehicleType_t	 vehicleType;
	Count_t	*cntSnapshots	/* OPTIONAL */;
	struct snapshots {
		A_SEQUENCE_OF(struct Snapshot) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} snapshots;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProbeVehicleData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProbeVehicleData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/VehicleIdent.h>
#include <SAE_J2735/Snapshot.h>

#endif	/* _ProbeVehicleData_H_ */
#include <SAE_J2735/asn_internal.h>
