/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_RegionList_H_
#define	_RegionList_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RegionOffsets;

/* RegionList */
typedef struct RegionList {
	A_SEQUENCE_OF(struct RegionOffsets) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RegionList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RegionList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/RegionOffsets.h>

#endif	/* _RegionList_H_ */
#include <SAE_J2735/asn_internal.h>
