/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_RoadSignID_H_
#define	_RoadSignID_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/Position3D.h>
#include <SAE_J2735/HeadingSlice.h>
#include <SAE_J2735/MUTCDCode.h>
#include <SAE_J2735/MsgCRC.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadSignID */
typedef struct RoadSignID {
	Position3D_t	 position;
	HeadingSlice_t	 viewAngle;
	MUTCDCode_t	*mutcdCode	/* OPTIONAL */;
	MsgCRC_t	*crc	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} __attribute__ ((packed)) RoadSignID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSignID;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadSignID_H_ */
#include <SAE_J2735/asn_internal.h>
