/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_RTCMmsg_H_
#define	_RTCMmsg_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/RTCM-Revision.h>
#include <SAE_J2735/RTCM-ID.h>
#include <SAE_J2735/RTCM-Payload.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RTCMmsg */
typedef struct RTCMmsg {
	RTCM_Revision_t	*rev	/* OPTIONAL */;
	RTCM_ID_t	*rtcmID	/* OPTIONAL */;
	RTCM_Payload_t	 payload;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTCMmsg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTCMmsg;

#ifdef __cplusplus
}
#endif

#endif	/* _RTCMmsg_H_ */
#include <SAE_J2735/asn_internal.h>
