/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_RTCM_Corrections_H_
#define	_RTCM_Corrections_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/MsgCount.h>
#include <SAE_J2735/RTCM-Revision.h>
#include <SAE_J2735/RTCMHeader.h>
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FullPositionVector;
struct RTCMmsg;

/* RTCM-Corrections */
typedef struct RTCM_Corrections {
	DSRCmsgID_t	 msgID;
	MsgCount_t	 msgCnt;
	RTCM_Revision_t	 rev;
	struct FullPositionVector	*anchorPoint	/* OPTIONAL */;
	RTCMHeader_t	 rtcmHeader;
	struct rtcmSets {
		A_SEQUENCE_OF(struct RTCMmsg) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rtcmSets;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RTCM_Corrections_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTCM_Corrections;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/FullPositionVector.h>
#include <SAE_J2735/RTCMmsg.h>

#endif	/* _RTCM_Corrections_H_ */
#include <SAE_J2735/asn_internal.h>
