/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_RTCMHeader_H_
#define	_RTCMHeader_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RTCMHeader */
typedef OCTET_STRING_t	 RTCMHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RTCMHeader;
asn_struct_free_f RTCMHeader_free;
asn_struct_print_f RTCMHeader_print;
asn_constr_check_f RTCMHeader_constraint;
ber_type_decoder_f RTCMHeader_decode_ber;
der_type_encoder_f RTCMHeader_encode_der;
xer_type_decoder_f RTCMHeader_decode_xer;
xer_type_encoder_f RTCMHeader_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RTCMHeader_H_ */
#include <SAE_J2735/asn_internal.h>
