/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_Sample_H_
#define	_Sample_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Sample */
typedef struct Sample {
	long	 sampleStart;
	long	 sampleEnd;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Sample_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Sample;

#ifdef __cplusplus
}
#endif

#endif	/* _Sample_H_ */
#include <SAE_J2735/asn_internal.h>
