/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_ShapePointSet_H_
#define	_ShapePointSet_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/LaneWidth.h>
#include <SAE_J2735/DirectionOfUse.h>
#include <SAE_J2735/NodeList.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Position3D;

/* ShapePointSet */
typedef struct ShapePointSet {
	struct Position3D	*anchor	/* OPTIONAL */;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	DirectionOfUse_t	*directionality	/* OPTIONAL */;
	NodeList_t	 nodeList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ShapePointSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShapePointSet;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/Position3D.h>

#endif	/* _ShapePointSet_H_ */
#include <SAE_J2735/asn_internal.h>
