/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_SignalRequestMsg_H_
#define	_SignalRequestMsg_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/MsgCount.h>
#include <SAE_J2735/SignalRequest.h>
#include <SAE_J2735/TransitStatus.h>
#include <SAE_J2735/BSMblob.h>
#include <SAE_J2735/VehicleRequestStatus.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DTime;
struct VehicleIdent;

/* SignalRequestMsg */
typedef struct SignalRequestMsg {
	DSRCmsgID_t	 msgID;
	MsgCount_t	 msgCnt;
	SignalRequest_t	 request;
	struct DTime	*timeOfService	/* OPTIONAL */;
	struct DTime	*endOfService	/* OPTIONAL */;
	TransitStatus_t	*transitStatus	/* OPTIONAL */;
	struct VehicleIdent	*vehicleVIN	/* OPTIONAL */;
	BSMblob_t	 vehicleData;
	VehicleRequestStatus_t	*status	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalRequestMsg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalRequestMsg;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/DTime.h>
#include <SAE_J2735/VehicleIdent.h>

#endif	/* _SignalRequestMsg_H_ */
#include <SAE_J2735/asn_internal.h>
