/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_SignalStatusMessage_H_
#define	_SignalStatusMessage_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/MsgCount.h>
#include <SAE_J2735/IntersectionID.h>
#include <SAE_J2735/IntersectionStatusObject.h>
#include <SAE_J2735/TransitStatus.h>
#include <SAE_J2735/SignalState.h>
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleIdent;

/* SignalStatusMessage */
typedef struct SignalStatusMessage {
	DSRCmsgID_t	 msgID;
	MsgCount_t	 msgCnt;
	IntersectionID_t	 id;
	IntersectionStatusObject_t	 status;
	struct priority {
		A_SEQUENCE_OF(SignalState_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *priority;
	struct VehicleIdent	*priorityCause	/* OPTIONAL */;
	struct prempt {
		A_SEQUENCE_OF(SignalState_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *prempt;
	struct VehicleIdent	*preemptCause	/* OPTIONAL */;
	TransitStatus_t	*transitStatus	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalStatusMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalStatusMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/VehicleIdent.h>

#endif	/* _SignalStatusMessage_H_ */
#include <SAE_J2735/asn_internal.h>
