/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_SnapshotTime_H_
#define	_SnapshotTime_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SnapshotTime */
typedef struct SnapshotTime {
	long	 t1;
	long	 s1;
	long	 t2;
	long	 s2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SnapshotTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SnapshotTime;

#ifdef __cplusplus
}
#endif

#endif	/* _SnapshotTime_H_ */
#include <SAE_J2735/asn_internal.h>
