/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_SPAT_H_
#define	_SPAT_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/DSRCmsgID.h>
#include <SAE_J2735/DescriptiveName.h>
#include <SAE_J2735/asn_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE_OF.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
//struct IntersectionState;

/* SPAT */
typedef struct SPAT {
	DSRCmsgID_t	 msgID;
	DescriptiveName_t	*name	/* OPTIONAL */;
	struct intersections1 {
		A_SEQUENCE_OF(struct IntersectionState) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} intersections1;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SPAT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SPAT;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/IntersectionState.h>

#endif	/* _SPAT_H_ */
#include <SAE_J2735/asn_internal.h>
