/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_SunSensor_H_
#define	_SunSensor_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SunSensor */
typedef long	 SunSensor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SunSensor;
asn_struct_free_f SunSensor_free;
asn_struct_print_f SunSensor_print;
asn_constr_check_f SunSensor_constraint;
ber_type_decoder_f SunSensor_decode_ber;
der_type_encoder_f SunSensor_encode_der;
xer_type_decoder_f SunSensor_decode_xer;
xer_type_encoder_f SunSensor_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SunSensor_H_ */
#include <SAE_J2735/asn_internal.h>
