/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_TermDistance_H_
#define	_TermDistance_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TermDistance */
typedef long	 TermDistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TermDistance;
asn_struct_free_f TermDistance_free;
asn_struct_print_f TermDistance_print;
asn_constr_check_f TermDistance_constraint;
ber_type_decoder_f TermDistance_decode_ber;
der_type_encoder_f TermDistance_encode_der;
xer_type_decoder_f TermDistance_decode_xer;
xer_type_encoder_f TermDistance_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TermDistance_H_ */
#include <SAE_J2735/asn_internal.h>
