/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_TractionControlState_H_
#define	_TractionControlState_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TractionControlState {
	TractionControlState_unavailable	= 0,
	TractionControlState_off	= 1,
	TractionControlState_on	= 2,
	TractionControlState_engaged	= 3
} e_TractionControlState;

/* TractionControlState */
typedef long	 TractionControlState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TractionControlState;
asn_struct_free_f TractionControlState_free;
asn_struct_print_f TractionControlState_print;
asn_constr_check_f TractionControlState_constraint;
ber_type_decoder_f TractionControlState_decode_ber;
der_type_encoder_f TractionControlState_encode_der;
xer_type_decoder_f TractionControlState_decode_xer;
xer_type_encoder_f TractionControlState_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TractionControlState_H_ */
#include <SAE_J2735/asn_internal.h>
