/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_ValidRegion_H_
#define	_ValidRegion_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/HeadingSlice.h>
#include <SAE_J2735/Extent.h>
#include <SAE_J2735/ShapePointSet.h>
#include <SAE_J2735/Circle.h>
#include <SAE_J2735/RegionPointSet.h>
#include <SAE_J2735/constr_CHOICE.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum area_PR {
	area_PR_NOTHING,	/* No components present */
	area_PR_shapePointSet,
	area_PR_circle,
	area_PR_regionPointSet
} area_PR;

/* ValidRegion */
typedef struct ValidRegion {
	HeadingSlice_t	 direction;
	Extent_t	*extent	/* OPTIONAL */;
	struct area {
		area_PR present;
		union ValidRegion__area_u {
			ShapePointSet_t	 shapePointSet;
			Circle_t	 circle;
			RegionPointSet_t	 regionPointSet;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} area;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ValidRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ValidRegion;

#ifdef __cplusplus
}
#endif

#endif	/* _ValidRegion_H_ */
#include <SAE_J2735/asn_internal.h>
