/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_VehicleSafetyExtension_H_
#define	_VehicleSafetyExtension_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/EventFlags.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PathHistory;
struct PathPrediction;
struct RTCMPackage;

/* VehicleSafetyExtension */
typedef struct VehicleSafetyExtension {
	EventFlags_t	*events	/* OPTIONAL */;
	struct PathHistory	*pathHistory	/* OPTIONAL */;
	struct PathPrediction	*pathPrediction	/* OPTIONAL */;
	struct RTCMPackage	*theRTCM	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSafetyExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSafetyExtension;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/PathHistory.h>
#include <SAE_J2735/PathPrediction.h>
#include <SAE_J2735/RTCMPackage.h>

#endif	/* _VehicleSafetyExtension_H_ */
#include <SAE_J2735/asn_internal.h>
