/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_VehicleStatusRequest_H_
#define	_VehicleStatusRequest_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/VehicleStatusDeviceTypeTag.h>
#include <SAE_J2735/NativeInteger.h>
#include <SAE_J2735/BOOLEAN.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleStatusRequest */
typedef struct VehicleStatusRequest {
	VehicleStatusDeviceTypeTag_t	 dataType;
	long	*subType	/* OPTIONAL */;
	long	*sendOnLessThenValue	/* OPTIONAL */;
	long	*sendOnMoreThenValue	/* OPTIONAL */;
	BOOLEAN_t	*sendAll	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleStatusRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleStatusRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleStatusRequest_H_ */
#include <SAE_J2735/asn_internal.h>
