/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_VehicleSize_H_
#define	_VehicleSize_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/VehicleWidth.h>
#include <SAE_J2735/VehicleLength.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSize */
typedef struct VehicleSize {
	VehicleWidth_t	 width;
	VehicleLength_t	 length;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSize_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSize;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSize_H_ */
#include <SAE_J2735/asn_internal.h>
