/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_VehicleLength_H_
#define	_VehicleLength_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleLength */
typedef long	 VehicleLength_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleLength;
asn_struct_free_f VehicleLength_free;
asn_struct_print_f VehicleLength_print;
asn_constr_check_f VehicleLength_constraint;
ber_type_decoder_f VehicleLength_decode_ber;
der_type_encoder_f VehicleLength_encode_der;
xer_type_decoder_f VehicleLength_decode_xer;
xer_type_encoder_f VehicleLength_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleLength_H_ */
#include <SAE_J2735/asn_internal.h>
