/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_VehicleLaneAttributes_H_
#define	_VehicleLaneAttributes_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleLaneAttributes */
typedef long	 VehicleLaneAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleLaneAttributes;
asn_struct_free_f VehicleLaneAttributes_free;
asn_struct_print_f VehicleLaneAttributes_print;
asn_constr_check_f VehicleLaneAttributes_constraint;
ber_type_decoder_f VehicleLaneAttributes_decode_ber;
der_type_encoder_f VehicleLaneAttributes_encode_der;
xer_type_decoder_f VehicleLaneAttributes_decode_xer;
xer_type_encoder_f VehicleLaneAttributes_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleLaneAttributes_H_ */
#include <SAE_J2735/asn_internal.h>
