/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_VehicleReferenceLane_H_
#define	_VehicleReferenceLane_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/LaneNumber.h>
#include <SAE_J2735/LaneWidth.h>
#include <SAE_J2735/VehicleLaneAttributes.h>
#include <SAE_J2735/NodeList.h>
#include <SAE_J2735/ConnectsTo.h>
#include <SAE_J2735/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NodeList;

/* VehicleReferenceLane */
typedef struct VehicleReferenceLane {
	LaneNumber_t	 laneNumber;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	VehicleLaneAttributes_t	 laneAttributes;
	NodeList_t	 nodeList;
	struct NodeList	*keepOutList	/* OPTIONAL */;
	ConnectsTo_t	*connectsTo	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleReferenceLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleReferenceLane;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <SAE_J2735/NodeList.h>

#endif	/* _VehicleReferenceLane_H_ */
#include <SAE_J2735/asn_internal.h>
