/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735.asn"
 */

#ifndef	_WheelEndElectFault_H_
#define	_WheelEndElectFault_H_


#include <SAE_J2735/asn_application.h>

/* Including external dependencies */
#include <SAE_J2735/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WheelEndElectFault {
	WheelEndElectFault_bitOne	= 1,
	WheelEndElectFault_bitTwo	= 2,
	WheelEndElectFault_bitThree	= 3,
	WheelEndElectFault_bitFour	= 4
} e_WheelEndElectFault;

/* WheelEndElectFault */
typedef BIT_STRING_t	 WheelEndElectFault_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WheelEndElectFault;
asn_struct_free_f WheelEndElectFault_free;
asn_struct_print_f WheelEndElectFault_print;
asn_constr_check_f WheelEndElectFault_constraint;
ber_type_decoder_f WheelEndElectFault_decode_ber;
der_type_encoder_f WheelEndElectFault_encode_der;
xer_type_decoder_f WheelEndElectFault_decode_xer;
xer_type_encoder_f WheelEndElectFault_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _WheelEndElectFault_H_ */
#include <SAE_J2735/asn_internal.h>
